Broken material repair config attempt.
Rebirth-of-the-Night/Rebirth-Of-The-Night pull request #935
Opened 2022-07-12 18:45 UTC by SpGilbert

I am running into problems of it breaking crafttweaker even if its just atop.zs. While aether.zs also breaks it. I added all diamond, ruby, alxeandrite, saphhire, zanite and gravitite gear to it.
[debug-2.log.gz](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9095957/debug-2.log.gz)
[2022-07-09-5.log.gz](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9095962/2022-07-09-5.log.gz)
[crash-2022-07-09_21.15.18-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9095967/crash-2022-07-09_21.15.18-client.txt)
[crash-2022-07-09_21.27.30-client.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/9095971/crash-2022-07-09_21.27.30-client.txt)

2022-07-12 18:46 UTC, SpGilbert commented
kind of a mess due to originaly putting it in the vanillanvil repair config. But I was told to split it to aether.zs and atop.zs later.

2022-07-12 18:50 UTC, democat3457 requested changes

2022-07-12 18:50 UTC, democat3457 commented on config/vanillaanvilrepair.cfg
> +>
revert this change

2022-07-12 18:50 UTC, democat3457 commented on scripts/aether.zs
> +var gravititeItems = <aether_legacy:gravitite_helmet> | <aether_legacy:gravitite_chestplate> | <aether_legacy:gravitite_leggings> | <aether_legacy:gravitite_boots. | <aether_legacy:gravitite_sword> |
```suggestion
var gravititeItems = <aether_legacy:gravitite_helmet> | <aether_legacy:gravitite_chestplate> | <aether_legacy:gravitite_leggings> | <aether_legacy:gravitite_boots> | <aether_legacy:gravitite_sword> | <atop:amber_pickaxe> |  <atop:amber_shovel> | <atop:amber_axe> | <spartancompat:battleaxe_gravitite> | <spartancompat:boomerang_gravitite> | <spartancompat:dagger_gravitite> | <spartancompat:glaive_gravitite> | <spartancompat:greatsword_gravitite> | <spartancompat:halberd_gravitite> | <spartancompat:hammer_gravitite> | <spartancompat:javelin_gravitite> | <spartancompat:katana_gravitite> | <spartancompat:lance_gravitite> | <spartancompat:longbow_gravitite> | <spartancompat:longsword_gravitite> | <spartancompat:mace_gravitite> | <spartancompat:pike_gravitite> | <spartancompat:rapier_gravitite> | <spartancompat:saber_gravitite> | <spartancompat:spear_gravitite> | <spartancompat:staff_gravitite> | <spartancompat:throwing_axe_gravitite> | <spartancompat:throwing_knife_gravitite> | <spartancompat:warhammer_gravitite>;
```

2022-07-12 18:54 UTC, SpGilbert commented
thanks for the fixes.

2022-07-13 06:27 UTC, democat3457 commented
> thanks for the fixes.

Can you actually implement those fixes? Those are just comments...

2022-07-13 06:28 UTC, democat3457 commented
Also, those crashes in the description are unrelated

2022-07-13 06:40 UTC, SpGilbert commented
implemented both.

2022-07-13 07:50 UTC, democat3457 commented
syntax-wise, looks good to me

@TheNelston can you read it over to make sure all the items are mapped to the right repair item

2022-07-13 20:46 UTC, merged